name: Buf CI
on:
  push:
    paths:
      - 'buf.yaml'
      - 'buf.lock'
      - 'proto/README.md'
      - 'proto/LICENSE'
      - 'proto/**.proto'
      - '.github/workflows/buf-ci.yaml'
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
  delete:
permissions:
  contents: read
  pull-requests: write
jobs:
  buf:
    # Ignore PRs from the 'fetch.yaml' action. Keep this branch name synced there.
    if: ${{ github.event_name != 'pull_request' || github.head_ref != 'fetch-modules' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-action@v0.2
        with:
          username: ${{ secrets.BUF_USER }}
          token: ${{ secrets.BUF_TOKEN }}
          push_create_visibility: public
          version: 1.34.0
