name: Buf CI
on:
  push:
    paths:
      - 'buf.yaml'
      - 'buf.lock'
      - 'proto/README.md'
      - 'proto/LICENSE'
      - 'proto/**.proto'
      - '.github/workflows/buf-ci.yaml'
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
    branches-ignore:
      - 'fetch-modules'
  delete:
permissions:
  contents: read
  pull-requests: write
jobs:
  buf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-action@v0.1
        with:
          username: ${{ secrets.BUF_USER }}
          token: ${{ secrets.BUF_TOKEN }}
          push_create_visibility: public
          version: 1.34.0
