name: Buf CI
on:
  push:
    paths:
      - 'proto/**'
permissions:
  contents: read
  pull-requests: write
jobs:
  buf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-action@v0.1
        with:
          username: ${{ secrets.BUF_USER }}
          token: ${{ secrets.BUF_TOKEN }}
          push_create_visibility: public
          version: 1.34.0
          input: proto
          breaking_against: |
            ${{ github.event.repository.clone_url }}#format=git,commit=${{ github.event.pull_request.base.sha }},subdir=proto
      - name: Run buf generate
        run: |
          buf generate --error-format github-actions
          git diff --exit-code private/gen/modules
