name: buf
on:
  push:
    paths:
      - 'proto/**'
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ github.token }}
      - uses: bufbuild/buf-lint-action@v1.0.3
        with:
          buf_token: ${{ secrets.BUF_TOKEN }}
  breaking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ github.token }}
      - uses: bufbuild/buf-breaking-action@v1.1.2
        with:
          against: 'https://github.com/bufbuild/modules.git#branch=main'
