name: ci
on:
  push:
  workflow_dispatch: {} # support manual runs

permissions:
  contents: read

concurrency: ci-${{ github.ref }}

jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.x
          check-latest: true
          cache: true
      - name: Test
        run: make test
      - name: Lint
        run: make checkgenerate && make lint
