name: Publish Release

on:
  schedule:
    # Fetch PRs are fired every weekday at morning. Do releases in the afternoon.
    # At 15:00 EST (20:00 UTC) on every day-of-week from Monday through Friday. https://crontab.guru/#0_20_*_*_1-5
    - cron: "0 20 * * 1-5"
  workflow_dispatch:

permissions:
  contents: write
  id-token: write
  packages: read

jobs:
  release:
    if: github.repository == 'bufbuild/modules'
    runs-on: ubuntu-22.04
    outputs:
      did_release: ${{ steps.release.outputs.did_release }}
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.x
          check-latest: true
          cache: true
      - name: Create Release
        id: release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        # Go command sets a $DID_RELEASE ENV var to "true" in case a release was produced.
        run: |
          go run ./cmd/release .
          echo "did_release=$DID_RELEASE" >> $GITHUB_OUTPUT
          cat $GITHUB_OUTPUT
  sync:
    needs: release
    environment: production
    if: github.repository == 'bufbuild/modules' && needs.release.outputs.did_release == 'true'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.x
          check-latest: true
          cache: true
      - name: Auth To GCP
        uses: google-github-actions/auth@ef5d53e30bbcd8d0836f4288f5e50ff3e086997d
        with:
          workload_identity_provider: projects/252484117105/locations/global/workloadIdentityPools/modules-workload-pool/providers/modules-workload-provider
          service_account: buf-modules-1-publisher@buf-modules-1.iam.gserviceaccount.com
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@62d4898025f6041e16b1068643bfc5a696863587
      - name: Upload To Release Bucket
        run: gsutil rsync -r modules/sync gs://buf-modules
