name: Publish Release

on:
  # schedule:
  #   - cron: "0 0 * * *" # Run once a day
  workflow_dispatch:

permissions:
  contents: write
  id-token: write
  packages: read

jobs:
  release:
    if: github.repository == 'bufbuild/modules'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.x
          check-latest: true
          cache: true
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          go run ./cmd/release .
