name: Sync to GCS

on:
  release:
    types: [published] # Sync GCS bucket everytime there's a new release.
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  release:
    environment: production
    if: github.repository == 'bufbuild/modules'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.x
          check-latest: true
          cache: true
      - name: Auth To GCP
        uses: google-github-actions/auth@ef5d53e30bbcd8d0836f4288f5e50ff3e086997d
        with:
          workload_identity_provider: projects/252484117105/locations/global/workloadIdentityPools/modules-workload-pool/providers/modules-workload-provider
          service_account: buf-modules-1-publisher@buf-modules-1.iam.gserviceaccount.com
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@62d4898025f6041e16b1068643bfc5a696863587
      - name: Upload To Release Bucket
        run: gsutil rsync -r modules/sync gs://buf-modules
